# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Bot"
    groups:
      github-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Bot"
    cooldown:
      default-days: 7
