name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --files ${{ steps.file_changes.outputs.files}}
