name: Save package versions

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Folium
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Create versions.txt
      shell: bash -l {0}
      run: |
        conda list > /tmp/versions.txt
        chromium --version >> /tmp/versions.txt

    - name: Save versions.txt
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: versions.txt
        path: /tmp/versions.txt
        fail-on-empty: false
      permissions:
        actions: write
