name: Notebook Style Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Notebook coding standards tests
      shell: bash -l {0}
      run: >
        for fname in examples/*.ipynb;
        do echo $fname $(flake8-nb $fname --ignore=W391,E226,E402,W504,I100,I201,I202,E703 --max-line-length=120 --show-source --count);
        done
