name: Geopandas tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Folium
      uses: actions/checkout@v4
      with:
        path: folium

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file folium/requirements.txt

    - name: Checkout Geopandas
      uses: actions/checkout@v4
      with:
        path: geopandas

    - name: Install Geopandas dev dependencies
      run: |
        pip install -r geopandas/requirements-dev.txt

    - name: Install folium from source
      run: |
        pwd && ls -la
        python -m pip install -e folium/ --no-deps --force-reinstall

    - name: Run Geopandas tests
      run: |
        pwd && ls -la
        pytest geopandas/geopandas/tests/test_explore.py
