name: Notebook Style Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@v14
      with:
        environment-file: false

    - name: Create env
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt --channel conda-forge
        micromamba activate TEST
        python -m pip install -e . --no-deps --force-reinstall

    - name: Notebook coding standards tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        for fname in examples/*.ipynb; do echo $fname $(flake8-nb $fname --ignore=W391,E226,E402,W504,I100,I201,I202,E703 --max-line-length=120 --show-source --count); done
