name: Geopandas tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Folium
      uses: actions/checkout@v4
      with:
        path: main

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt

    - name: Checkout Geopandas
      uses: actions/checkout@v4
      with:
        repository: geopandas/geopandas
        ref: main
        path: geopandas  # Checkout into a subdirectory

    - name: Install Geopandas dev dependencies
      run: |
        pip install -r geopandas/requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: |
        pwd && ls -la
        python -m pip install -e . --no-deps --force-reinstall

    - name: Run Geopandas tests
      run: |
        cd geopandas
        pwd && ls -la
        pytest geopandas/tests/test_explore.py
